### ISSUE TITLE
Unable to install LittlstarSDK_iOS

### ISSUE THREAD

**Issue by rakeshchintha** [littlstar/littlstar-ios-sdk#2]
I get the following error in the terminal when i update the podfile and run the pod install command as mentioned in the installation section.

``` javascript
Analyzing dependencies
[!] Unable to find a specification for `LittlstarSDK`
```

**Comment by marcshilling** [comment]
Same here, had to manually download zip and import it into project.

**Comment by marcshilling** [comment]
Add `source 'https://github.com/littlstar/Specs.git'` to the top of your podfile and it should work
