### ISSUE TITLE
Excessive logging when gyro is on

### ISSUE THREAD

**Issue by RyanCopley** [littlstar/littlstar-ios-sdk#3]
When you have the gyro mode on, it floods the console with coordinate logs. Could there be an option added to hide this please?

**Comment by marcshilling** [comment]
Same - would love to be able to disable the logging

**Comment by jwerle** [comment]
@RyanCopley @marcshilling the latest build should fix this

**Comment by marcshilling** [comment]
Confirmed that it's fixed in 2.0.9...thanks!

**Comment by jwerle** [comment]
np!
