### ISSUE TITLE
Unable to build on 4s simulator because of SDWebImage requirement

### ISSUE THREAD

**Issue by marcshilling** [littlstar/littlstar-ios-sdk#4]
Installed via Cocoapods...here is my podfile:

```
pod 'LittlstarSDK', '~> 2.0'
pod 'SDWebImage', '~> 3.7'
```

I can build for every simulator except the 4s because of the following error:

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SDWebImageManager", referenced from:
      objc-class-ref in libLittlstarSDK.a(LSPlayerView.o)
```

**Comment by jwerle** [comment]
@marcshilling weird... we'll investigate shortly

**Comment by marcshilling** [comment]
Hmm...this randomly started working for me again. I believe upgrading to the Cocoapods 1.0.0 beta was the difference.

**Comment by jwerle** [comment]
interesting... yeah we couldn't reproduce on our end. we're glad it is working

**Comment by ilosqut** [comment]
The problem is still exist, can't find resolution
